### ISSUE TITLE
Rank selector cuts off on smaller screens

### ISSUE THREAD

**Issue by LuminescentBlade** [saylith/feh-tier-list-generator#4]
<img width="268" alt="screen shot 2017-10-29 at 11 02 44 am" src="https://user-images.githubusercontent.com/2934535/32145059-c59be520-bc98-11e7-9302-d3c87bb4bfe6.png">

I cannot select S, and SS is entirely cut off. I use a standard 13 in macbook fullsized. Please make the selection bar a bit more responsive, like go on to a second line if the first won't fit.

**Comment by saylith** [comment]
Hi LuminescentBlade,

I think this should be fixed with a5ba93e

Let me know if that works better for you.

**Comment by LuminescentBlade** [comment]
Works well, thanks!
